name: fair_compiler
description: A complier which can generate Fair bundle for widget with annotation.
version: 0.3.1+1
homepage: https://fair.58.com/

environment:
  sdk: ^2.13.4
  flutter: ^2.2.3

#executables:
#  fairc:
dependencies:
  source_gen: ^1.0.2
  build: ^2.0.2
  crypto: ^3.0.1
  build_config: ^1.0.0
  process: ^4.2.1
  archive: ^3.1.2
  intl: ^0.17.0
  path: ^1.6.4
  analyzer: ^1.7.1
  dart_style: ^2.0.1
  glob: ^2.0.1
  pedantic: ^1.8.0
  fair_annotation: ^0.2.0
  http: ^0.13.3

dev_dependencies:
  test: ^1.6.0
